services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: snake-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: snake-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
